language: java

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

addons:
  apt_packages:
    - git

jdk:
  - oraclejdk11
  - oraclejdk8
  - openjdk7

env:
  - BUILD="mvn install"
  - BUILD="gradle publishToMavenLocal exec"

matrix:
  fast_finish: true

# To avoid "gradle assemble"; gradle version provided doesn't
# work with Java 10.  Remove when gradle gets updated.
install:
  - true

script:
  - $BUILD

# Exclude gradle/java 10 combination until gradle is updated.
matrix:
  fast_finish: true
  exclude:
    - jdk: oraclejdk10
      env: BUILD="gradle publishToMavenLocal exec"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8
    condition: $BUILD = "mvn install"
